version: "3.1"
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: myjenkins
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins:/var/jenkins_home
volumes:
  jenkins: